version: "3.8"
services:
  backend-app:
    build:
      context: ./
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - database
    env_file: ./backend/.env
    restart: always
    networks:
      - mynetwork
  database:
    image: postgres:latest
    env_file: ./backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5452:5432"
    restart: always
    networks:
      - mynetwork
  frontend-app:
    build:
      context: ./
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend-app
    restart: always
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge
volumes:
  postgres_data: