version: '3.8'
services:
  backend:
    container_name: flask-backend
    build:
      context: ./backend
      dockerfile: ./backend/docker/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - database
    env_file: ./backend/.env
    restart: always
    networks:
      - mynetwork

  database:
    container_name: postgres-db
    image: postgres:latest
    env_file: ./backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: always
    networks:
      - mynetwork


  frontend:
    container_name: react-frontend
    image: node:14
    working_dir: /app
    command: "npm start"
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data:
